### ISSUE TITLE
cairo_copy_path?

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/Cairo.jl#103]
Would it be possible to add support for `cairo_copy_path()` and `cairo_copy_path_flat()` at some point in the future? These functions return the current Cairo path. See [Cairo documentation](http://cairographics.org/manual/cairo-Paths.html).

I'm thinking that it would be a useful way of accessing type outlines - use `text_path()` (already in Cairo.jl) to convert text to a path, and then `copy_path()` to retrieve the path for subsequent use.

**Comment by timholy** [comment]
Want to put together a pull request?

**Comment by cormullion** [comment]
ah, Tim, I would love to be smart enough to know what to put in such a pull request...I'm just a beginner.

**Comment by lobingera** [comment]
@cormullion: Please keep in mind, that Cairo.jl uses a combined pangocairo solution to paint text and not the cairo-only text functions. So not all glyph outlines will be accessible as cairo path. 
Apart from that, if i find time (next week) i could do a PR for both these calls and the respective cairo_path_t.

**Comment by lobingera** [comment]
Intermediate: Getting the calls isn't the issue. Cairo uses a data structure for the path (and entries) that seems to fall into the 'julia types are not c-structs' domain.

**Comment by lobingera** [comment]
#106 
tries to enstablish this.

**Comment by cormullion** [comment]
@lobingera Wow, that looks just the ticket! Will investigate asap. Thanks!

**Comment by cormullion** [comment]
Should I close this?  Will the package be updated/released (to v0.2.28?) for use with Julia version 0.3.9?

**Comment by lobingera** [comment]
@timholy ?

**Comment by timholy** [comment]
Done.

**Comment by cormullion** [comment]
@timholy @lobingera thanks!
