### ISSUE TITLE
Explain use of local install?

### ISSUE THREAD

**Issue by andrewcooke** [JuliaLang/Cairo.jl#115]
It's possible (I don't understand the install process in any detail) that Pkg.add() uses a local install of cairo, if it's available.  Even if not, building and installing cairo requires multiple libraries.  So it seems advisable to first install cairo locally, if you are using an OS where that is easy (eg Linux w package manager), since that "pulls in" the required dependencies.

So maybe it's worth adding something on the front page (README.md) saying something like:

*Pkg.add("Cairo") will attempt to compile the cairo library if it is not already present on your computer.  This is a large, complex library with multiple dependencies.  So please consider whether installing cairo locally (eg by using a package manager) would simplify (and accelerate) the install.*

(I didn't add it myself because, as I say above, I am unsure about exactly how it works).

**Comment by andrewcooke** [comment]
OK, so some more experimenting suggests that it doesn't work as I thought.  So perhaps:

*Pkg.add("Cairo") will attempt to compile the cairo library. This is a large, complex library with multiple dependencies. You may need to install these dependencies and restart the install with Pkg.build("Cairo").  If you use a package manager, one useful way of installing the required dependencies is to install a local version of the cairo library (or perhaps the associated dev package).*

**Comment by kmsquire** [comment]
This behavior is probably true of most packages that use BinDeps: they'll look for a local install first, and if that doesn't exist, will find some other source to install from.

**Comment by andrewcooke** [comment]
yeah, it seems the root cause of my confusion is that BinDeps is not finding libraries on opensuse.  i am going to poke around some more and may raise an issue there instead.

**Comment by andrewcooke** [comment]
https://github.com/JuliaLang/BinDeps.jl/issues/164

**Comment by andrewcooke** [comment]
https://github.com/JuliaLang/Cairo.jl/pull/116/files
