### ISSUE TITLE
Installation issue Windows 7 64 bit Julia 0.4.3

### ISSUE THREAD

**Issue by adijkstra** [JuliaLang/Cairo.jl#132]
When upgrading Julia to 0.4.3 I am unable to install Cairo. Originally there was a download error from WinRPM, but that seems fixed by updating sources.list. Cairo still won't build though.
 
Fixes I've tried:
- updating sources.list from WindowsRPM to the warwick mirror. 
- Removing .julia folder and reinstalling all packages. 
- Pkg.update()
- Pkg.checkout("WinRPM", "tk/cache")

`julia> versioninfo()`
Julia Version 0.4.3
Commit a2f713d (2016-01-12 21:37 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

`julia> Pkg.checkout("WinRPM", "tk/cache")`
INFO: Checking out WinRPM tk/cache...
warning: CRLF will be replaced by LF in sources.list.
The file will have its original line endings in your working directory.
ERROR: WinRPM is dirty, bailing
 in error at error.jl:21

`julia> Pkg.installed()`
Dict{ASCIIString,VersionNumber} with 44 entries:
  "ImmutableArrays"   => v"0.0.11"
  "ArrayViews"        => v"0.6.4"
  "DataStructures"    => v"0.4.2"
  "Compat"            => v"0.7.9"
  "Calculus"          => v"0.1.14"
  "GZip"              => v"0.2.18"
  "StatsFuns"         => v"0.2.0"
  "Measures"          => v"0.0.2"
  "Cairo"             => v"0.2.31"
  "DataFrames"        => v"0.6.10"
  "Showoff"           => v"0.0.6"
  "Distributions"     => v"0.8.10"
  "LibExpat"          => v"0.1.2"
  "FixedPointNumbers" => v"0.1.1"
  "SHA"               => v"0.1.2"
  "DualNumbers"       => v"0.2.1"
  "KernelDensity"     => v"0.1.2"
  "Iterators"         => v"0.1.9"
  "ColorTypes"        => v"0.2.0"
  "Gadfly"            => v"0.4.2"
  "Dates"             => v"0.4.4"
  "Contour"           => v"0.0.8"
  "PDMats"            => v"0.4.0"
  "Optim"             => v"0.4.4"
  "SortingAlgorithms" => v"0.0.6"
  "WinRPM"            => v"0.1.13"
  "Docile"            => v"0.5.23"
  "WoodburyMatrices"  => v"0.1.5"
  "Grid"              => v"0.4.0"
  "JSON"              => v"0.5.0"
  "StatsBase"         => v"0.7.4"
  "Hexagons"          => v"0.0.4"
  "Distances"         => v"0.3.0"
  "Loess"             => v"0.0.6"
  "BinDeps"           => v"0.3.21"
  "Reexport"          => v"0.0.3"
  "Graphics"          => v"0.1.3"
  "URIParser"         => v"0.1.2"
  "NaNMath"           => v"0.2.0"
  "Compose"           => v"0.4.2"
  "DataArrays"        => v"0.2.20"
  "Colors"            => v"0.6.2"
  "Zlib"              => v"0.1.12"
  "Codecs"            => v"0.1.5"

`julia> Pkg.build("Cairo")`
INFO: Building WinRPM
INFO: Downloading ftp://anorien.csc.warwick.ac.uk/download.opensuse.org/reposito
ries/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.xml
INFO: Downloading ftp://anorien.csc.warwick.ac.uk/download.opensuse.org/reposito
ries/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.xml
INFO: Building Cairo
INFO: Updating WinRPM package list
INFO: Downloading ftp://anorien.csc.warwick.ac.uk/download.opensuse.org/reposito
ries/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.xml
INFO: Downloading ftp://anorien.csc.warwick.ac.uk/download.opensuse.org/reposito
ries/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.xml
INFO: Nothing to do
================================[ ERROR: Cairo ]================================

LoadError: Provider WinRPM.RPM failed to satisfy dependency gobject
while loading C:\Users\user\.julia\v0.4\Cairo\deps\build.jl, in expression start
ing on line 144

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Cairo had build errors.

 - packages with build errors remain installed in C:\Users\user\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("Cairo")`
 - build a single package by running its `deps/build.jl` script

================================================================================

`julia> BinDeps.debug("Cairo")`
INFO: Reading build script...
The package declares 1 dependencies.
 - Library Group "cairo"
     - Library "png" (not applicable to this system)
     - Library "pixman" (not applicable to this system)
     - Library "ffi" (not applicable to this system)
     - Library "gettext" (not applicable to this system)
     - Library "gobject"
        - Providers:
          - WinRPM.RPM package glib2
          - WinRPM.RPM package libgobject-2_0-0
          - BinDeps.AptGet package libglib2.0-0 (can't provide)
          - BinDeps.Yum package glib2 (can't provide)
          - Autotools Build
     - Library "freetype" (not applicable to this system)
     - Library "fontconfig" (not applicable to this system)
     - Library "cairo"
        - Providers:
          - WinRPM.RPM package libcairo2
          - WinRPM.RPM package libharfbuzz0
          - BinDeps.AptGet package libcairo2 (can't provide)
          - BinDeps.Yum package cairo (can't provide)
          - Autotools Build
     - Library "pango"
        - Providers:
          - WinRPM.RPM package libpango-1_0-0
          - BinDeps.AptGet package libpango1.0-0 (can't provide)
          - BinDeps.Yum package pango (can't provide)
          - Autotools Build
     - Library "pangocairo"
        - Providers:
          - WinRPM.RPM package libpango-1_0-0
          - BinDeps.AptGet package libpango1.0-0 (can't provide)
          - BinDeps.Yum package pango (can't provide)
          - Autotools Build
     - Library "zlib"
        - Satisfied by:
          - System Paths at C:\Users\user\Anaconda2\Library\bin\zlib.DLL
          - System Paths at C:\Users\user\Anaconda2\Library\bin\zlib.dll
          - System Paths at C:\Users\user\AppData\Local\Julia-0.4.3\bin\zlib1.DL
L
          - System Paths at C:\Users\user\AppData\Local\Julia-0.4.3\bin\zlib1.dl
l
        - Providers:
          - WinRPM.RPM package zlib-devel
          - Simple Build Process

**Comment by tkelman** [comment]
Thanks for the report. I don't see anything as having changed in the library names for this on the opensuse build service (https://build.opensuse.org/package/show/windows:mingw:win64/mingw64-glib2), so it must be due to the recent BinDeps tag. Try `Pkg.pin("BinDeps", v"0.3.20")` and see if that works. I can reproduce this locally and I'm bisecting to try to find the cause.

**Comment by adijkstra** [comment]
'Pkg.pin("BinDeps", v"0.3.20")' solves the issue for me.

**Comment by tkelman** [comment]
You can do `Pkg.free("BinDeps"); Pkg.update()` and this should be fixed now.
