### ISSUE TITLE
Pkg.add("Cairo") fails on Windows 7

### ISSUE THREAD

**Issue by Ken-B** [JuliaLang/Cairo.jl#71]
My fresh Julia installation fails to build Cairo. Error points to `pango`. Tried on 2 different internet connections and I'm able to reach http://ftp.acc.umu.se/pub/GNOME/sources/pango/1.32/.

This prevents me from plotting with Winston :( 
Let me know what I can do to test further. Thanks.

``` julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" to list help topics
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.0-rc1+82 (2014-07-18 22:02 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 876e0d3 (1 day old master)
|__/                   |  x86_64-w64-mingw32


In  [3]: Pkg.build("Cairo")
INFO: Building LibCURL
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Factory//repodata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Factory//repodata/repomd.xml
INFO: Building WinRPM
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Factory//repodata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Factory//repodata/repomd.xml
INFO: Building Cairo
================================[ ERROR: Cairo ]================================

None of the selected providers can install dependency pango
while loading C:\Users\K\.julia\v0.3\Cairo\deps\build.jl, in expression starting on line 129

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Cairo had build errors.

 - packages with build errors remain installed in C:\Users\K\.julia\v0.3
 - build a package and all its dependencies with `Pkg.build(pkg)`
 - build a single package by running its `deps/build.jl` script

================================================================================

In  [4]: versioninfo()
Julia Version 0.3.0-rc1+82
Commit 876e0d3 (2014-07-18 22:02 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2677M CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by DougFirErickson** [comment]
Running those commands, I get the following error related to download utilities:

`INFO: Reading build script...
ERROR: LoadError: No download agent available; install curl, wget, or fetch.
 in download_cmd at C:\Users\adam\.julia\v0.4\BinDeps\src\BinDeps.jl:75
 [inlined code] from C:\Users\adam\.julia\v0.4\BinDeps\src\BinDeps.jl:251
 in lower at C:\Users\adam\.julia\v0.4\BinDeps\src\BinDeps.jl:337
 [inlined code] from C:\Users\adam\.julia\v0.4\BinDeps\src\BinDeps.jl:251
 in generate_steps at C:\Users\adam\.julia\v0.4\BinDeps\src\dependencies.jl:365
 in lower at C:\Users\adam\.julia\v0.4\BinDeps\src\dependencies.jl:279
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in debug_context at C:\Users\adam\.julia\v0.4\BinDeps\src\debug.jl:54
 in debug at C:\Users\adam\.julia\v0.4\BinDeps\src\debug.jl:59
 in debug at C:\Users\adam\.julia\v0.4\BinDeps\src\debug.jl:65
while loading C:\Users\adam\.julia\v0.4\Cairo\deps\build.jl, in expression start
ing on line 251`

**Comment by tkelman** [comment]
@DougFirErickson what does `Pkg.status()` say?

**Comment by DougFirErickson** [comment]
I've since resolved the issue with the help of this [thread](https://github.com/JuliaLang/WinRPM.jl/issues/27#issuecomment-183779364). There is a known issue with WinRPM on Windows if you are located in Europe. Basically, the default "OpenSUSE" IP address forwards to an outdated mirror. So, you can either manually update the sources list to a server in Germany or you can re-initiate WinRPM, restart Julia, run WinRPM.update(), then Pkg.build("Cairo"). The latter worked for me on the first try and now Jupyter functions nicely.
