### ISSUE TITLE
Design Decisions, interfaces with Gtk?

### ISSUE THREAD

**Issue by lobingera** [JuliaLang/Cairo.jl#95]
(well, not really an issue, but to have a discussion)

Cairo.jl is in most cases a thin layer on the libcairo. cairo has only a few basic datastructures, like the context, surfaces etc. so they are created as types mostly containing a pointer only.

For the context the designers of Cairo.jl decided to have not only a pointer to the cairo context, but also a pointer to a pango (libpango for text rendering) layout. 

I'm trying to use a Gtk/Cairo mixture to do some interactive GUI stuff (for plotting actually) and i see some problems with that. The problems show up, as Gtk Widgets usually contain a cairo context, but no pango layout. Some signal/event handling in Gtk returns the cairo context, only. So in my code i need to recreate a full julia-Cairo.jl CairoContext by creating and allocating a pango layout to be fully compatible. And it a lot of cases when only drawing is needed, but no text (and there is a simple text rendering in cairo already) this looks like creating some overhead.

Would it be a general issue to discard the pango layout from CairoContext and have text rendering split into a cairo only and pango flavour?

**Comment by lobingera** [comment]
No discussion.

**Comment by timholy** [comment]
Sorry, but I don't know enough about this to contribute meaningfully. If you've studied the problem, you're way ahead of me.
