### ISSUE TITLE
svg stream not closed in REPL

### ISSUE THREAD

**Issue by kubaroth** [JuliaLang/Cairo.jl#96]
This problem only occurs when writing svg file from the running REPL. If the session is closed the svg file is closed correctly.
I'm not sure it I'm supposed to deal with the opened file by Cairo myself?

Below lines are enough to reproduce my issue.
path = "test.svg"
s = CairoSVGSurface(path,256,256);
sr = CairoContext(s);
save (sr)

Thanks,
kuba

**Comment by lobingera** [comment]
You need to call finish(s). Afaics when closing the REPL the destroy operation for the surface is called via finalize. It's not documented, but it looks like flush+finish are called within that also.

**Comment by kubaroth** [comment]
Thanks, that solved my problem.
