### ISSUE TITLE
Cannot draw to Array with CairoImageSurface

### ISSUE THREAD

**Issue by michael-p** [JuliaLang/Cairo.jl#97]
Dear all,

I'm trying to draw to a Julia Array{Uint32,2} using CairoImageSurface but the array does not get changed at all. For example:

```
using Cairo

function fill_red(surface)
  ctx = CairoContext(surface)
  set_source_rgb(ctx, 1.0, 0.0, 0.0)
  paint(ctx)
end

img_data = zeros(Uint32, (84, 84))
surface = CairoImageSurface(img_data, Cairo.FORMAT_RGB24)
println(status(surface))  # prints 0 (=Cairo.STATUS_SUCCESS)
fill_red(surface)
# now inspect img_data in the REPL -> still all zeros

# This works
surface2 = CairoRGBSurface(84, 84)
fill_red(surface2)
write_to_png(surface2, "red.png")
```
img_data isn't changed at all whereas the second part produces the file red.png as expected.
Am I doing something wrong here or is this a bug?
I use Julia 0.3.2 on OSX 10.9.5.

Thanks,
Michael

**Comment by michael-p** [comment]
Two updates:
1.) This does not help:
```
ccall((:cairo_surface_flush, Cairo._jl_libcairo), Void, (Ptr{Void},), surface.ptr)
```

2.) A dirty hacky work-around is the following:
```
result = Array(Uint32, (84, 84))
data_ptr = ccall((:cairo_image_surface_get_data, Cairo._jl_libcairo), Ptr{Uint32}, (Ptr{Void},), surface2.ptr)
for i = 1:length(result)
  result[i] = unsafe_load(data_ptr, i)
end
```

Anyone an idea what is going on here?

**Comment by lobingera** [comment]
I had a similar behaviour when working on the example in 
https://groups.google.com/forum/#!searchin/julia-users/cairo/julia-users/wG1g9C7S6Mg/zx9Pqntv1e0J

Afaics you can access the data in the surface.data entry. Which is setup in the call to CairoSurface (with 4 entries) and should actually be the same like the input data field, but it isn't. Looking at this for longer, looks like julia is passing a copy and this copy is setup as .data.

**Comment by michael-p** [comment]
Thanks Andreas, this does indeed work! I first tried the CairoImageSurface-constructor with just width, height, and format, but there the data-field is undefined. So you have to pass in an array which does not get updated but then at least the data field is there and contains, well, the data :)
I find this behavior a bit confusing but will close this issue anyway. Feel free to reopen.

**Comment by lobingera** [comment]
I'm using something like this (painting to a data field) in a python program. But also reading the cairo API documentation it's not very clear if the input is copied in any case. From a gut feeling i'd say that copying is here an side effect of the defined interface. I'm not a master of the julia API relations (you see some stupid questions about ccall from me on the julia-users...).
I can only guess that the datafiled in the surface type was put there for access.
But we would need an oldschooler to answer this.

**Comment by lobingera** [comment]
btw. i cannot reopen this, you or one of the project heads can.
